spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-classclasspath-name: com.mysql.cj.jdbc.Driver
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
  jms:
    pub-sub-domain: true
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml


